# Place recognition models
cosplace:
  output: "global-feats-cosplace"
  model:
    name: "cosplace"
    backbone: "EfficientNet_B0"
    fc_output_dim: 512
    checkpoint_path: "efficientnet_85x85.pth"
